export const zh = {
  app: {
    initializing: '正在初始化本地文献库...',
    browserPreview: '浏览器预览模式无法调用桌面文件导入，请打开桌面版。',
    readyEmpty: '本地文献库已就绪，请从 PDF 导入第一篇文献。',
    loaded: (count: number) => `已加载 ${count} 篇本地文献。`,
    initFailed: '本地文献库初始化失败，请检查应用数据目录权限。',
    chooseFirst: '请先选择一个 PDF 文件。',
    importSuccess: '导入成功，PDF 已复制到本地文献库。',
    importDuplicate: '这篇文献已存在，已为你打开已有记录。',
    importFailed: '导入失败，请确认 PDF 文件存在且可读取。',
    saveSuccess: '已保存文献信息。',
    saveFailed: '保存失败，请稍后重试。',
    deleteSuccess: '已删除文献。',
    deleteFailed: '删除失败，请稍后重试。',
    actionFailed: '操作失败，请检查文件权限或稍后重试。',
  },
  scenes: {
    overview: '总览',
    library: '文献库',
    reader: '阅读',
    ai: 'AI 对话',
    settings: '设置',
  },
  command: {
    title: '命令面板',
    openShortcut: '命令面板 Ctrl+K',
    placeholder: '搜索命令、场景或操作',
    empty: '没有匹配的命令',
    groupLibrary: '文献库',
    groupReader: '阅读',
    groupScenes: '场景',
    groupWorkspace: '工作台',
    importPdf: '从 PDF 导入',
    searchLibrary: '搜索文献库',
    openOverview: '打开总览',
    openLibrary: '打开文献库',
    openReader: '打开阅读',
    openAi: '打开 AI 对话',
    openSettings: '打开设置',
    openNotesPanel: '打开笔记面板',
    openAnnotationsPanel: '打开标注面板',
    openChatPanel: '打开对话面板',
    openRelationsPanel: '打开关系面板',
  },
  library: {
    recentImport: (title: string) => `最近导入：${title}`,
    title: '文献库',
    subtitle: '导入、检索和整理本地论文。',
    shortcutsHint: '快捷键：Ctrl+K 命令面板，Ctrl+O 导入，Ctrl+F 搜索，Ctrl+Enter 阅读，Ctrl+1/2/3/4 切换场景。',
    importPdf: '从 PDF 导入',
    importTranslationPdf: '导入译文 PDF',
    translationImported: '译文 PDF 已绑定到当前文献。',
    translationImportFailed: '译文 PDF 导入失败，请确认文件可读取。',
    search: '搜索标题、作者、标签或笔记',
    edit: '编辑',
    tagsEdit: '标签',
    delete: '删除',
    details: '详情',
    hideDetails: '收起详情',
    viewRelations: '关系',
    selectAll: '选择当前列表全部文献',
    selectPaper: (title: string) => `选择《${title}》`,
    bulkSelected: (count: number) => `已选择 ${count} 篇`,
    bulkEditTags: '批量标签',
    bulkDelete: '批量删除',
    clearSelection: '清空选择',
    copyMarkdown: '复制清单',
    copyCsv: '复制 CSV',
    copyBibtex: '复制 BibTeX',
    copyMarkdownSuccess: (count: number) => `已复制 ${count} 篇文献的 Markdown 清单。`,
    copyCsvSuccess: (count: number) => `已复制 ${count} 篇文献的 CSV 清单。`,
    copyBibtexSuccess: (title: string) => `已复制《${title}》的 BibTeX。`,
    copyBulkBibtexSuccess: (count: number) => `已复制 ${count} 篇文献的 BibTeX。`,
    copyFailed: '复制失败，请检查剪贴板权限。',
    bulkTagsTitle: '批量编辑标签',
    bulkTagsHint: '保存后会用这里的标签替换所选文献的标签。',
    bulkTagsSaved: (count: number) => `已更新 ${count} 篇文献的标签。`,
    bulkDeleteSuccess: (count: number) => `已删除 ${count} 篇文献。`,
    deleteConfirmTitle: '删除文献',
    bulkDeleteConfirmTitle: '批量删除文献',
    confirmBulkDelete: (count: number) => `确定删除选中的 ${count} 篇文献吗？这些文献的文件、笔记、标注和 AI 记录都会一起删除。`,
    morePapers: (count: number) => `...还有 ${count} 篇`,
    openReader: '阅读',
    tableTitle: '标题',
    tableAuthors: '作者',
    tableYear: '年份',
    tableVenue: '来源',
    tableTags: '标签',
    unknownAuthors: '未知作者',
    unknownVenue: '未知来源',
    emptyTitle: '文献库还是空的',
    emptyDescription: '点击“从 PDF 导入”，A4Note 会复制文件、提取标题等元数据，并写入本地 SQLite。',
    noMatchTitle: '没有匹配的文献',
    noMatchDescription: '可以清空搜索或切回全部标签。',
    tags: '标签',
    all: '全部',
    files: '文件',
    revealFile: '显示',
    openExternal: '外部打开',
    revealSourceFailed: '无法定位原文 PDF，请检查文件是否仍在资料库中。',
    revealTranslatedFailed: '无法定位译文 PDF，请检查文件是否仍在资料库中。',
    openSourceFailed: '无法打开原文 PDF，请检查系统默认 PDF 应用。',
    openTranslatedFailed: '无法打开译文 PDF，请检查系统默认 PDF 应用。',
    bindings: '绑定内容',
    relations: '关系图谱',
    bound: '已绑定',
    unbound: '未绑定',
    translationCount: (count: number) => `${count} 份译文`,
    noteCount: (count: number) => `${count} 条笔记`,
    annotationCount: (count: number) => `${count} 条标注`,
    aiThreadCount: (count: number) => `${count} 个对话`,
    objectCount: (count: number) => `${count} 个对象`,
    relationCount: (count: number) => `${count} 条关系`,
    fileObjectCount: (count: number) => `${count} 个文件对象`,
    relationPreview: '关系预览',
    relationPreviewEmpty: '当前文献还没有可展示的关系。',
    relationMore: (count: number) => `还有 ${count} 条关系，可在阅读器关系面板查看。`,
    selected: (title: string) => `已选中：${title}`,
    noSelection: '选中一篇文献后，可以编辑、改标签或进入阅读。',
    openHint: '双击文献可直接进入阅读。',
    confirmDelete: (title: string) => `确定删除《${title}》吗？该文献的文件、笔记、标注和 AI 记录都会一起删除。`,
  },
  editDialog: {
    title: '编辑文献信息',
    tagsTitle: '编辑标签',
    close: '关闭',
    save: '保存',
    cancel: '取消',
    paperTitle: '论文标题',
    authors: '作者',
    year: '年份',
    venue: '期刊 / 会议',
    doi: 'DOI',
    tags: '标签',
    tagsHint: '输入标签后回车，可搜索已有标签；没有匹配时会直接新建。',
  },
  importDialog: {
    selecting: '正在等待选择 PDF...',
    eyebrow: 'PDF 导入',
    title: '从 PDF 自动生成文献草稿',
    close: '关闭',
    selectStep: '1. 选择 PDF',
    extractStep: '2. 自动提取',
    confirmStep: '3. 修改或确认',
    choosePdf: '选择 PDF 文件',
    chooseAnother: '重新选择',
    selectedFile: '已选择文件',
    noFile: '尚未选择文件',
    extracting: '正在从 PDF 和文件名提取标题、作者、年份、DOI...',
    ready: '已生成草稿。可以修改，也可以直接确认导入。',
    idle: '选择 PDF 后会自动生成可编辑草稿。',
    error: '自动提取失败，但仍可根据文件名草稿继续导入。',
    openFailed: '无法打开系统文件选择器，请检查桌面权限或重启应用。',
    sourcePdfText: '来源：PDF 内容',
    sourceFilename: '来源：文件名',
    sourceManual: '来源：手动填写',
    titleField: '论文标题',
    authors: '作者',
    year: '年份',
    venue: '期刊 / 会议',
    doi: 'DOI',
    tags: '标签',
    optional: '可稍后补全',
    optionalDoi: '可选',
    tagsPlaceholder: '输入标签后回车',
    regenerate: '重新提取',
    onlineEnrich: '在线补全',
    onlineLoading: '补全中...',
    onlineFailed: '在线补全失败，已保留当前草稿。',
    onlineSuccess: (source: string) => `在线补全成功：${source}`,
    onlineDisabled: '已在设置中关闭在线补全。',
    importFailedInline: '导入失败，请确认 PDF 文件仍存在且可读取。',
    untitledDocument: '未命名文献',
    confirm: '确认导入',
    importing: '导入中...',
    hint: '确认后会复制 PDF 到应用数据目录，写入 SQLite，并立即显示在文献库中。',
  },
  reader: {
    title: '阅读',
    focusLayout: '专注',
    noteLayout: '笔记',
    aiLayout: 'AI',
    highlight: '高亮',
    comment: '批注',
    underline: '下划线',
    area: '区域框选',
    textBox: '文本框',
    ink: '自由画笔',
    eraser: '橡皮擦',
    rect: '矩形',
    arrow: '箭头',
    cursor: '鼠标',
    pdfMode: 'PDF',
    markdownMode: 'Markdown',
    sourcePdf: '原文',
    translatedPdf: '译文',
    parallelPdf: '对照',
    parallelSync: '同步滚动',
    translatedFileSelect: '选择译文 PDF',
    translatedFileOption: (index: number) => `译文 ${index}`,
    zoomOut: '缩小',
    zoomIn: '放大',
    fitWidth: '适应宽度',
    panelNotes: '笔记',
    panelAnnotations: '标注',
    panelChat: '对话',
    panelRelations: '引用',
    openPanel: '打开工作面板',
    closePanel: '关闭',
    noteTitle: '绑定的 Markdown 笔记',
    noteDefaultTitle: '阅读笔记',
    noteNumberedTitle: (index: number) => `阅读笔记 ${index}`,
    noteHistory: '全部笔记',
    noteHistoryCount: (count: number) => `${count} 篇笔记`,
    noteNew: '新建笔记',
    noteReadingMode: '阅读模式',
    noteEditingMode: '编辑模式',
    noteTitlePlaceholder: '笔记标题',
    noteEmpty: '还没有笔记',
    notePlaceholder: '# 阅读笔记\n\n- 核心观点\n- 方法细节\n- 后续问题',
    noteEdit: '编辑',
    notePreview: '预览',
    saveNote: '保存',
    noteSaved: '已保存',
    noteUnsaved: '有未保存修改',
    noteSaving: '正在保存...',
    noteSaveError: '保存失败',
    appendAnnotationToNote: '引用到笔记',
    markdownEmptyTitle: '还没有 Markdown 笔记',
    markdownEmptyDescription: '可以先创建一条与当前文献绑定的阅读笔记。',
    createNote: '创建阅读笔记',
    noPaperTitle: '还没有可阅读的文献',
    noPaperDescription: '请先在文献库导入一篇 PDF，然后再进入阅读场景。',
    aiAssist: 'AI 辅助',
    aiContextBound: (count: number) => `${count} 条标注已绑定到当前文献，可作为 AI 上下文。`,
    pdfLoading: '正在加载 PDF...',
    pdfPlaceholder: '导入真实 PDF 后，会在这里渲染内部文献库文件。',
    pdfError: '无法渲染这份 PDF，请检查文件是否仍在 A4Note 文献库中。',
    annotationHint: '鼠标工具可选择复制文字；高亮、下划线、矩形、箭头和自由画笔请拖拽创建；文本框点击页面后输入内容；橡皮擦点击标注删除。阅读快捷键：Ctrl+=/- 缩放，Ctrl+0 适应宽度，Ctrl+M/H/U/T/P/E/R/A 切换工具。',
    commentAnnotation: '批注',
    commentLabel: '批注',
    underlineLabel: '下划线',
    areaLabel: '区域框选',
    textLabel: '文本框',
    inkLabel: '自由画笔',
    rectLabel: '矩形',
    arrowLabel: '箭头',
    highlightLabel: '高亮',
    commentPlaceholder: '输入批注内容...',
    saveComment: '保存',
    cancelComment: '取消',
    noAnnotations: '还没有标注。',
    relationSummary: (objects: number, relations: number) => `${objects} 个对象，${relations} 条关系。`,
    relationFiles: '文件关系',
    relationNotes: '笔记关系',
    relationAnnotations: '当前文件标注',
    relationAiThreads: 'AI 对话',
    relationNoNotes: '还没有绑定笔记。',
    relationNoAnnotations: '当前文件还没有标注。',
    relationNoAi: '还没有绑定 AI 对话。',
    relationMoreAnnotations: (count: number) => `还有 ${count} 条标注未显示，可在标注面板查看。`,
    deleteAnnotation: '删除',
    undo: '撤销',
    annotationCreated: '标注已保存',
    annotationDeleted: '标注已删除',
    annotationDeletePending: '标注已移除，可撤销。',
    annotationDeleteUndone: '已撤销删除',
    annotationDeleteUndoMessage: '标注已移除，将在几秒后确认删除。',
    annotationCreateFailed: '标注保存失败，请重试。',
    annotationSaveFailed: '批注保存失败，已恢复原内容。',
    annotationDeleteFailed: '标注删除失败，已恢复。',
    annotationPage: (page: number) => `第 ${page} 页`,
    pageStatus: (current: number, total: number) => `${current} / ${total}`,
  },
  ai: {
    title: 'AI 对话',
    subtitle: '围绕当前文献、笔记和标注进行本地上下文对话。',
    provider: '本地上下文助手',
    noPaperTitle: '还没有可绑定的文献',
    noPaperDescription: 'AI 对话会围绕文献、笔记和标注建立上下文。请先导入 PDF。',
    boundTopics: (count: number) => `${count} 个绑定话题`,
    context: '当前上下文',
    newThread: '新会话',
    resetConfirmTitle: '清空 AI 对话',
    confirmReset: '确定清空当前文献的本地 AI 对话记录吗？文献、PDF、笔记和标注不会被删除。',
    noPdf: '尚未绑定 PDF',
    input: '基于当前文献上下文提问...',
    send: '发送',
    saveFailed: '对话已显示，但保存到本地资料库失败。请检查数据库权限后重试。',
    resetFailed: '清空 AI 对话失败，本地记录已保留。请检查数据库权限后重试。',
    systemMessage: (count: number, provider: string) => `当前 AI Provider：${provider}。我可以使用已绑定的 PDF、Markdown 笔记和 ${count} 条标注。`,
    userPrompt: '提取和我研究问题最相关的部分。',
    providerHint: '对话会保存到本地资料库，并始终绑定当前 paper_id。',
  },
  settings: {
    title: '设置',
    subtitle: '管理界面、资料库和插件能力。',
    language: '语言',
    density: '界面密度',
    defaultReaderLayout: '默认阅读布局',
    metadataSources: '元数据补全',
    library: '资料库',
    plugins: '插件能力',
    about: '关于 A4Note',
    extensionSummary: '当前版本启用本地可信插件模型，先开放内部扩展点，后续再做插件市场和沙箱。',
    extensionCommands: '命令',
    extensionEvents: '事件',
    extensionSettings: '设置项',
    extensionViews: '视图',
    extensionMetadata: '元数据源',
    extensionTranslation: '翻译源',
    extensionAi: 'AI Provider',
    extensionEnabled: '可用',
    extensionReserved: '已预留',
    extensionLocalOnly: '本地可信',
    builtInProviders: '内置 Provider',
    noRegisteredPlugins: '尚未安装第三方插件',
    registeredPlugins: '已注册插件',
    pluginCount: (count: number) => `${count} 个插件`,
    chinese: '中文',
    compact: '紧凑',
    comfortable: '舒适',
    crossrefFirst: 'Crossref 优先',
    arxivFirst: 'arXiv 优先',
    localOnly: '仅本地提取',
    enableOnlineMetadata: '启用在线补全',
    localLibrary: '单一本地资料库 / SQLite',
    libraryRoot: '资料库根目录',
    databasePath: '数据库',
    filesPath: '文件库',
    copyPath: '复制',
    copyDiagnostics: '复制诊断信息',
    openLibraryRoot: '打开资料库',
    openFilesPath: '打开文件库',
    openBackupsPath: '打开备份',
    refreshPaths: '刷新路径',
    createBackup: '创建资料库备份',
    backupRunning: '正在备份...',
    backupCreated: '备份已创建',
    backupFailed: '备份失败，请检查资料库目录权限',
    restoreBackup: '从备份恢复',
    restoreRunning: '正在恢复...',
    restoreSuccess: (safetyBackupPath: string) => `已恢复资料库。恢复前的资料库已自动备份到：${safetyBackupPath}`,
    restoreFailed: '恢复失败，请确认选择的是包含 aster.db 的 A4Note 备份目录。',
    restoreUnavailable: '浏览器预览模式无法恢复资料库，请打开桌面版。',
    restoreConfirmTitle: '恢复资料库',
    confirmRestore: '确定从这个备份恢复资料库吗？当前资料库会先自动备份，然后被所选备份替换。',
    pathCopied: '路径已复制',
    diagnosticsCopied: '诊断信息已复制',
    pathCopyFailed: '复制失败',
    pathUnavailable: '尚未加载',
    productName: '产品',
    version: '版本',
    identifier: '标识',
    platform: '平台',
    dataRoot: '数据目录',
    paperCount: '文献数',
    sourcePdfCount: '原文 PDF',
    translatedPdfCount: '译文 PDF',
    noteCount: '笔记数',
    annotationCount: '标注数',
    aiThreadCount: 'AI 对话',
    missingFileCount: '缺失文件',
    databaseSize: '数据库大小',
    filesSize: '文件库大小',
  },
};
